### ISSUE TITLE
您好！想问一下，这个是什么原理啊

### ISSUE THREAD

**Issue by linxian1998** [Licoy/fetch-github-hosts#1]

**Comment by linxian1998** [comment]
可以具体讲一讲吗！

**Comment by Licoy** [comment]
@linxian1998 在`README`中已经介绍了：

> 此项目是通过部署此项目本身的服务器来获取 github.com 的 hosts，而不是通过第三方ip地址接口来进行获取，例如 ipaddress.com 等

[参考](https://github.com/Licoy/fetch-github-hosts#%E5%8E%9F%E7%90%86)

**Comment by linxian1998** [comment]
thanks，还想问一下项目本身的服务器是在国内做了github源的镜像吗？所以可以很快打开，还是有其他的操作，可能本人不太理解具体为什么会导致平时访问github很慢，想请教一下

**Comment by Licoy** [comment]
@Licoy 部署此项目的服务器不在国内，是非大陆节点，假设部署的服务器是韩国或日本，那么就可以获取到github的日本或韩国节点IP，这样再由国内访问github速度就比较快。

**Comment by linxian1998** [comment]
好的，非常感谢您

**Comment by ddkwork** [comment]
利用国外服务器治理dns污染的意思嘛？呵呵
