### ISSUE TITLE
[Openwrt]sed: unsupported command Q

### ISSUE THREAD

**Issue by HumanMus1c** [Licoy/fetch-github-hosts#10]
在openwrt终端运行时
![image](https://github.com/Licoy/fetch-github-hosts/assets/46023154/c03150ce-a344-4bd3-8b13-3ee835522863)

**Comment by HumanMus1c** [comment]
解决了：
将“Q”改为":wq"
`sed -i "/# fetch-github-hosts begin/:wq" /etc/hosts && curl https://hosts.gitcdn.top/hosts.txt >> /etc/myhosts`

![image](https://github.com/Licoy/fetch-github-hosts/assets/46023154/d2a75fff-8db4-4b29-a441-016c6917f25b)

**Comment by aobenny** [comment]
感谢指引！
