### ISSUE TITLE
域名hosts.gitcdn.top被墙了

### ISSUE THREAD

**Issue by yindynasty** [Licoy/fetch-github-hosts#18]
域名hosts.gitcdn.top被墙了

**Comment by Licoy** [comment]
并没有喔，因为`hosts.gitcdn.top`使用了cloudflare的cdn，但是cloudflare分配此域名给大陆的访问ip无法ping通，所以造成了无法访问的现象，由于目前有一些软件将`hosts.gitcdn.top`嵌入到了系统，进行频繁的获取数据，所以我们暂时不得进行其他的方式进行处理。
