### ISSUE TITLE
请支持magisk使用

### ISSUE THREAD

**Issue by ariagecheney** [Licoy/fetch-github-hosts#2]
需求:
手机端看一些 github 相关的东西 , 总是破图,不显示;   
(不想总是飞机).

问题描述:
miui 13.0.3 ,  termux 0.118.0 ;
给了777权限 和 su 执行;
报错:
**更新Github-Hosts失败：获取最新的hosts失败: Get "https://hosts.gitcdn.top/hosts.txt": dial tcp: lookup hosts.gitcdn.top on [::1]:53: read udp [::1]:48231->[::1]:53: read: connection refused** 

其他:
电脑端(linux/mac/window)均正常;

**Comment by Licoy** [comment]
从错误信息来看好像是网络不能解析，你切换到github520源试试呢？

**Comment by Licoy** [comment]
先关闭，有问题再打开
