### ISSUE TITLE
Linux版本怎么直接是压缩包 ，目录结构是/usr开头的

### ISSUE THREAD

**Issue by liaojiaao** [Licoy/fetch-github-hosts#21]
linux版本的程序.tar.xg 解压出来是/usr开头，该怎么安装，然后，如果我直接解压到  / 根目录下，有个MakeFile在 / 根目录下
这个文件结构，不知道该怎么办

**Comment by Licoy** [comment]
直接找到对应的二进制进行运行就可以了，因为这个是gui的
