### ISSUE TITLE
访问接口https://hosts.gitcdn.top/hosts.txt超时

### ISSUE THREAD

**Issue by OuterCloud** [Licoy/fetch-github-hosts#3]
有些时候访问不了https://hosts.gitcdn.top/hosts.txt
这个网站

requests.exceptions.ConnectionError: HTTPSConnectionPool(host='hosts.gitcdn.top', port=443): Max retries exceeded with url: /hosts.txt (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10a21c3d0>: Failed to establish a new connection: [Errno 60] Operation timed out'))

有时候可以访问，好像不是很稳定。
希望可以稳定，辛苦了。

**Comment by Licoy** [comment]
`hosts.gitcdn.top`有使用Cloudflare的CDN，可能有时候访问不稳定，如果要追求高稳定可以参考自建部分进行自行搭建或使用其他源。
