### ISSUE TITLE
windows10一键更新脚本

### ISSUE THREAD

**Issue by Tesla-AC** [Licoy/fetch-github-hosts#6]
```
@echo off
set curpath=%~dp0
cd %curpath%
set filename=hosts
set url=https://hosts.gitcdn.top/hosts.txt
powershell curl -o "%filename%" "%url%"
copy .\%filename% C:\Windows\System32\drivers\etc\hosts
ipconfig /flushdns
```

**Comment by youxuecao** [comment]
确实可以把hosts中添加git的ip 但是我hosts原有的东西没了。。。

**Comment by Licoy** [comment]
这个脚本应该会直接覆盖原文件吧，所以不太建议使用

**Comment by youxuecao** [comment]
竟然可以联系到作者&nbsp; 脚本确实会替换！ 感谢您的提醒建议fetch-github-hosts工具能够打开软件后直接启动 因为这样我就可以设置开机自启动了 不知道合不合适 纯粹个人想法
&nbsp;


李旭
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月5日(星期四) 下午4:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Licoy/fetch-github-hosts] windows10一键更新脚本 (Issue #6)





 
这个脚本应该会直接覆盖原文件吧，所以不太建议使用

**Comment by Licoy** [comment]
@youxuecao 可以考虑支持

**Comment by youxuecao** [comment]
感谢&nbsp;


李旭
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月5日(星期四) 下午4:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Licoy/fetch-github-hosts] windows10一键更新脚本 (Issue #6)





 
@youxuecao 可以考虑支持

**Comment by Licoy** [comment]
[a7250bb](https://github.com/Licoy/fetch-github-hosts/commit/a7250bb67c7a2050bbe49aaca261c379bcca2c54) 中已添加启动时自动获取功能，等下个版本发布即可

**Comment by Licoy** [comment]
[v2.6](https://github.com/Licoy/fetch-github-hosts/releases/tag/v2.6) 中已支持
